// <auto-generated />
using System;
using AgroShield.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroShield.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroShield.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("FarmId", "CreatedAt")
                        .HasDatabaseName("ix_alerts_farm_id_created_at")
                        .HasFilter("farm_id IS NOT NULL");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_alerts_user_id_is_read_created_at");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("RfidTag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rfid_tag");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("species");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_animals");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_animals_farm_id");

                    b.HasIndex("RfidTag")
                        .IsUnique()
                        .HasDatabaseName("ix_animals_rfid_tag")
                        .HasFilter("rfid_tag IS NOT NULL");

                    b.ToTable("animals", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.AnimalActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.HasKey("Id")
                        .HasName("pk_animal_activities");

                    b.HasIndex("AnimalId", "DetectedAt")
                        .HasDatabaseName("ix_animal_activities_animal_id_detected_at");

                    b.ToTable("animal_activities", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Anomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<int>("FrozenBatchesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("frozen_batches_count");

                    b.Property<int?>("GraphRiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("graph_risk_score");

                    b.Property<DateTime?>("LastFreezeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_freeze_at");

                    b.Property<string>("MlFeaturesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ml_features_json");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.Property<Guid[]>("RelatedFarmIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("related_farm_ids");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_anomalies");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_anomalies_farm_id");

                    b.HasIndex("Status", "DetectedAt")
                        .HasDatabaseName("ix_anomalies_status_detected_at");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_session_id_created_at");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_chat_sessions_user_id_updated_at");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_codes");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_email_verification_codes_email");

                    b.ToTable("email_verification_codes", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActiveAreaFromNdvi")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("active_area_from_ndvi");

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("area_hectares");

                    b.Property<string>("BankBin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bank_bin");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crop_type");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<Guid?>("ElevatorContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("elevator_contract_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NdviHistoryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ndvi_history_json");

                    b.Property<decimal?>("NdviMean")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("ndvi_mean");

                    b.Property<DateTime?>("NdviUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ndvi_updated_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerIin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("owner_iin");

                    b.Property<string>("PolygonGeoJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("polygon_geo_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<int>("RiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("risk_score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.HasIndex("BankBin")
                        .HasDatabaseName("ix_farms_bank_bin")
                        .HasFilter("bank_bin IS NOT NULL");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_farms_device_id")
                        .HasFilter("device_id IS NOT NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_farms_owner_id");

                    b.HasIndex("OwnerIin")
                        .HasDatabaseName("ix_farms_owner_iin")
                        .HasFilter("owner_iin IS NOT NULL");

                    b.HasIndex("RiskScore")
                        .HasDatabaseName("ix_farms_risk_score");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.FertilizerRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApplicationWindows")
                        .HasColumnType("jsonb")
                        .HasColumnName("application_windows");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("EstimatedCostKzt")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_cost_kzt");

                    b.Property<decimal?>("ExpectedYieldIncreasePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("expected_yield_increase_pct");

                    b.Property<string>("ExplanationRu")
                        .HasColumnType("text")
                        .HasColumnName("explanation_ru");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<decimal?>("KKgPerHa")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("k_kg_per_ha");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_version");

                    b.Property<decimal?>("NKgPerHa")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("n_kg_per_ha");

                    b.Property<decimal?>("PKgPerHa")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("p_kg_per_ha");

                    b.Property<decimal?>("TotalKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_kg");

                    b.HasKey("Id")
                        .HasName("pk_fertilizer_recommendations");

                    b.HasIndex("FarmId", "CreatedAt")
                        .HasDatabaseName("ix_fertilizer_recommendations_farm_id_created_at");

                    b.ToTable("fertilizer_recommendations", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("embedding_json");

                    b.Property<string>("SourceDoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_doc");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_chunks");

                    b.HasIndex("SourceDoc")
                        .HasDatabaseName("ix_knowledge_chunks_source_doc");

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Livestock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AnomalyDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("anomaly_detected");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeclaredCount")
                        .HasColumnType("integer")
                        .HasColumnName("declared_count");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime?>("LastDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_detected_at");

                    b.Property<int?>("LastDetectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_detected_count");

                    b.Property<string>("LastImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_image_url");

                    b.Property<string>("LivestockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("livestock_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_livestock");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_livestock_farm_id");

                    b.ToTable("livestock", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.LivestockLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entry_hash");

                    b.Property<string>("EventType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("LivestockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("livestock_type");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prev_hash");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_livestock_ledger");

                    b.HasIndex("EntryHash")
                        .IsUnique()
                        .HasDatabaseName("ix_livestock_ledger_entry_hash");

                    b.HasIndex("FarmId", "CreatedAt")
                        .HasDatabaseName("ix_livestock_ledger_farm_id_created_at");

                    b.ToTable("livestock_ledger", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.NotificationSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_subscriptions");

                    b.HasIndex("UserId", "NotificationType")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_subscriptions_user_id_notification_type");

                    b.ToTable("notification_subscriptions", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.PlantDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("disease");

                    b.Property<string>("DiseaseRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("disease_ru");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_healthy");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recommendation");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("severity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_plant_diagnoses");

                    b.HasIndex("FarmId", "CreatedAt")
                        .HasDatabaseName("ix_plant_diagnoses_farm_id_created_at");

                    b.HasIndex("IsHealthy", "CreatedAt")
                        .HasDatabaseName("ix_plant_diagnoses_is_healthy_created_at")
                        .HasFilter("is_healthy = false");

                    b.ToTable("plant_diagnoses", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_recommendations");

                    b.HasIndex("FarmId", "Status", "Priority")
                        .HasDatabaseName("ix_recommendations_farm_id_status_priority");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_sensors_farm_id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("Fire")
                        .HasColumnType("boolean")
                        .HasColumnName("fire");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("humidity");

                    b.Property<int>("Light")
                        .HasColumnType("integer")
                        .HasColumnName("light");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Temp")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temp");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("integer")
                        .HasColumnName("water_level");

                    b.HasKey("Id")
                        .HasName("pk_sensor_readings");

                    b.HasIndex("FarmId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sensor_readings_farm_id_recorded_at");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Subsidy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActiveAreaFromNdvi")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("active_area_from_ndvi");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CropType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("crop_type");

                    b.Property<decimal>("DeclaredArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("declared_area");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<Guid?>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<decimal?>("NdviMeanScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("ndvi_mean_score");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("approved")
                        .HasColumnName("workflow_status");

                    b.HasKey("Id")
                        .HasName("pk_subsidies");

                    b.HasIndex("WorkflowStatus")
                        .HasDatabaseName("ix_subsidies_workflow_status");

                    b.HasIndex("FarmId", "Status")
                        .HasDatabaseName("ix_subsidies_farm_id_status");

                    b.HasIndex("Status", "CheckedAt")
                        .HasDatabaseName("ix_subsidies_status_checked_at")
                        .HasFilter("checked_at IS NULL");

                    b.ToTable("subsidies", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SubsidyTranche", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AmountKzt")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount_kzt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<decimal>("PercentOfTotal")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percent_of_total");

                    b.Property<string>("ReleaseEvidenceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("release_evidence_json");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubsidyId")
                        .HasColumnType("uuid")
                        .HasColumnName("subsidy_id");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unlock_condition");

                    b.HasKey("Id")
                        .HasName("pk_subsidy_tranches");

                    b.HasIndex("Status", "UnlockCondition")
                        .HasDatabaseName("ix_subsidy_tranches_status_unlock_condition");

                    b.HasIndex("SubsidyId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_subsidy_tranches_subsidy_id_order");

                    b.ToTable("subsidy_tranches", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_supply_chain_audit_log");

                    b.HasIndex("PerformedBy")
                        .HasDatabaseName("ix_supply_chain_audit_log_performed_by");

                    b.HasIndex("Action", "PerformedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_action");

                    b.HasIndex("BatchId", "PerformedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_batch_time");

                    b.ToTable("supply_chain_audit_log", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AnomalyDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("anomaly_detected");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("batch_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("crop_type");

                    b.Property<string>("CurrentHolderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_holder_id");

                    b.Property<string>("CurrentHolderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("farm")
                        .HasColumnName("current_holder_type");

                    b.Property<decimal>("CurrentWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("current_weight_kg");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("FreezeReason")
                        .HasColumnType("text")
                        .HasColumnName("freeze_reason");

                    b.Property<DateTime?>("FrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_at");

                    b.Property<Guid?>("FrozenBy")
                        .HasColumnType("uuid")
                        .HasColumnName("frozen_by");

                    b.Property<DateOnly?>("HarvestDate")
                        .HasColumnType("date")
                        .HasColumnName("harvest_date");

                    b.Property<decimal>("InitialWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("initial_weight_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UnfrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unfrozen_at");

                    b.Property<Guid?>("UnfrozenBy")
                        .HasColumnType("uuid")
                        .HasColumnName("unfrozen_by");

                    b.HasKey("Id")
                        .HasName("pk_supply_chain_batches");

                    b.HasIndex("BatchCode")
                        .IsUnique()
                        .HasDatabaseName("ix_supply_chain_batches_batch_code");

                    b.HasIndex("FarmId", "Status")
                        .HasDatabaseName("ix_supply_chain_batches_farm_id_status");

                    b.HasIndex("Status", "FarmId")
                        .HasDatabaseName("ix_batches_status_farm");

                    b.ToTable("supply_chain_batches", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entry_hash");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prev_hash");

                    b.HasKey("Id")
                        .HasName("pk_supply_chain_ledger");

                    b.HasIndex("EntryHash")
                        .HasDatabaseName("ix_supply_chain_ledger_hash");

                    b.HasIndex("BatchId", "CreatedAt")
                        .HasDatabaseName("ix_supply_chain_ledger_batch_time");

                    b.ToTable("supply_chain_ledger", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_entity_name");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspicious");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("previous_hash");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ToEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_entity_id");

                    b.Property<string>("ToEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to_entity_name");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("transaction_hash");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_supply_chain_nodes");

                    b.HasIndex("TransactionHash")
                        .IsUnique()
                        .HasDatabaseName("ix_supply_chain_nodes_transaction_hash");

                    b.HasIndex("IsSuspicious", "TransactionDate")
                        .HasDatabaseName("ix_supply_chain_nodes_is_suspicious_transaction_date");

                    b.ToTable("supply_chain_nodes", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("FromNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_node_id");

                    b.Property<string>("FromNodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_node_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ToNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_node_id");

                    b.Property<string>("ToNodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_node_type");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transferred_at");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_supply_chain_transitions");

                    b.HasIndex("BatchId", "TransferredAt")
                        .HasDatabaseName("ix_supply_chain_transitions_batch_id_transferred_at");

                    b.ToTable("supply_chain_transitions", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssignedRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_region");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Farmer")
                        .HasColumnName("role");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("telegram_username");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AssignedRegion")
                        .HasDatabaseName("ix_users_assigned_region")
                        .HasFilter("assigned_region IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TelegramChatId")
                        .HasDatabaseName("ix_users_telegram_chat_id")
                        .HasFilter("telegram_chat_id IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.WeeklyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid[]>("FarmIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("farm_ids");

                    b.Property<string>("ReportMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_markdown");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id")
                        .HasName("pk_weekly_reports");

                    b.HasIndex("UserId", "WeekStart")
                        .HasDatabaseName("ix_weekly_reports_user_id_week_start");

                    b.ToTable("weekly_reports", (string)null);
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Alert", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.User", null)
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_users_user_id");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Animal", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("Animals")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animals_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.AnimalActivity", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Animal", "Animal")
                        .WithMany("Activities")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animal_activities_animals_animal_id");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Anomaly", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("Anomalies")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anomalies_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.User", null)
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_sessions_users_user_id");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Farm", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.User", "Owner")
                        .WithMany("OwnedFarms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farms_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.FertilizerRecommendation", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("FertilizerRecommendations")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fertilizer_recommendations_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Livestock", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("Livestock")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_livestock_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.LivestockLedger", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_livestock_ledger_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.NotificationSubscription", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.PlantDiagnosis", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("PlantDiagnoses")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plant_diagnoses_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("Recommendations")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("Sensors")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Subsidy", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("Subsidies")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subsidies_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SubsidyTranche", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Subsidy", "Subsidy")
                        .WithMany("Tranches")
                        .HasForeignKey("SubsidyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subsidy_tranches_subsidies_subsidy_id");

                    b.Navigation("Subsidy");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainAuditLog", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.SupplyChainBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supply_chain_audit_log_supply_chain_batches_batch_id");

                    b.HasOne("AgroShield.Domain.Entities.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supply_chain_audit_log_users_performed_by");

                    b.Navigation("Batch");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainBatch", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.Farm", "Farm")
                        .WithMany("SupplyChainBatches")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supply_chain_batches_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainTransition", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.SupplyChainBatch", "Batch")
                        .WithMany("Transitions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supply_chain_transitions_supply_chain_batches_batch_id");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.WeeklyReport", b =>
                {
                    b.HasOne("AgroShield.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_reports_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Animal", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Anomalies");

                    b.Navigation("FertilizerRecommendations");

                    b.Navigation("Livestock");

                    b.Navigation("PlantDiagnoses");

                    b.Navigation("Recommendations");

                    b.Navigation("Sensors");

                    b.Navigation("Subsidies");

                    b.Navigation("SupplyChainBatches");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.Subsidy", b =>
                {
                    b.Navigation("Tranches");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.SupplyChainBatch", b =>
                {
                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("AgroShield.Domain.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ChatSessions");

                    b.Navigation("OwnedFarms");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
